spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cardtrading
    username: cardtrading
    password: cardtrading

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    com.cardtrading: DEBUG
    org.springframework.security: DEBUG

management:
  endpoint:
    health:
      show-details: always
