ALTER TYPE card_rarity ADD VALUE 'BASE' AFTER 'SECRET';
ALTER TYPE card_rarity ADD VALUE 'RAINBOW' AFTER 'BASE';
ALTER TYPE card_rarity ADD VALUE 'GLITTER' AFTER 'RAINBOW';
ALTER TYPE card_rarity ADD VALUE 'CRYSTAL_SHINE' AFTER 'GLITTER';
ALTER TYPE card_rarity ADD VALUE 'GOLDEN_GLITTER' AFTER 'CRYSTAL_SHINE';
